import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en suppressHydrationWarning">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <Navbar />
          <div>
            <div className="mx-[min(5vw,50px)] mt-3">{children}</div>
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
